### PR TITLE
Fix Next on Spend / Earn > 950

### LINKED ISSUE #950: Next button not working on Spend page
https://www.loom.com/share/7c853237857442d6b5b5f53a366fd5cb

### PR DESCRIPTION
**Pull request by thejoefriel**
#### Issues this PR relates to
Fix #950 

Also fixed the permanent loading icon on some earn groups if they are online only 

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist
Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)
- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

### CODE REVIEW

File: client/src/pages/Staff/SingleProgramme/DetailsAndStatsSection.js [hunk 1]
```diff
@@ -98,7 +98,7 @@ const DetailsAndStatsSection = ({ id, details, stats, history, loading }) => (
         />
         <Stats
           size="s"
-          statNum={stats.spendPercVenues}
+          statNum={20.3333424234324234}
```
Comment (dupreesi) [inline client/src/pages/Staff/SingleProgramme/DetailsAndStatsSection.js:101]: I think this should go back to statNum={stats.spendPercVenues} ?
