### PR TITLE
1014 bug

### LINKED ISSUE #1014: Spend Activities not dissappearing from spend venue page when they are draft.
Loom Video of issue: https://www.loom.com/share/697d949dc22940e1b8cfb1ebfabbbc58

Hi, as explained in the video - spend activities that are draft are still appearing on the associated spend venue page, meaning I can find them when logged in as an earn-group or member.

### PR DESCRIPTION
**Pull request by thejoefriel**
#### Issues this PR relates to
Fix #1014 #1015 #1019 

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist
Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)
- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

### CODE REVIEW

File: client/src/pages/AcceptTimeCredits/actions.js [hunk 1]
```diff
@@ -16,6 +16,7 @@ export const getActivities = () => async (dispatch) => {
   dispatch({ type: GET_SPEND_ACTIVITIES_TO_ACCEPT_LOADING_START });
   try {
     const { data, error } = await activities.getActivities();
+    console.log("da", data);
```
Comment (RamyAlshurafa) [inline client/src/pages/AcceptTimeCredits/actions.js:19]:
```suggestion
```
